//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryAgent) DeepCopyInto(out *FoundryAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryAgent.
func (in *FoundryAgent) DeepCopy() *FoundryAgent {
	if in == nil {
		return nil
	}
	out := new(FoundryAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundryAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryAgentList) DeepCopyInto(out *FoundryAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundryAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryAgentList.
func (in *FoundryAgentList) DeepCopy() *FoundryAgentList {
	if in == nil {
		return nil
	}
	out := new(FoundryAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundryAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryAgentObservation) DeepCopyInto(out *FoundryAgentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryAgentObservation.
func (in *FoundryAgentObservation) DeepCopy() *FoundryAgentObservation {
	if in == nil {
		return nil
	}
	out := new(FoundryAgentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryAgentParameters) DeepCopyInto(out *FoundryAgentParameters) {
	*out = *in
	if in.MCPTools != nil {
		in, out := &in.MCPTools, &out.MCPTools
		*out = make([]MCPTool, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryAgentParameters.
func (in *FoundryAgentParameters) DeepCopy() *FoundryAgentParameters {
	if in == nil {
		return nil
	}
	out := new(FoundryAgentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryAgentSpec) DeepCopyInto(out *FoundryAgentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryAgentSpec.
func (in *FoundryAgentSpec) DeepCopy() *FoundryAgentSpec {
	if in == nil {
		return nil
	}
	out := new(FoundryAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryAgentStatus) DeepCopyInto(out *FoundryAgentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryAgentStatus.
func (in *FoundryAgentStatus) DeepCopy() *FoundryAgentStatus {
	if in == nil {
		return nil
	}
	out := new(FoundryAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryVectorStore) DeepCopyInto(out *FoundryVectorStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryVectorStore.
func (in *FoundryVectorStore) DeepCopy() *FoundryVectorStore {
	if in == nil {
		return nil
	}
	out := new(FoundryVectorStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundryVectorStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryVectorStoreList) DeepCopyInto(out *FoundryVectorStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FoundryVectorStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryVectorStoreList.
func (in *FoundryVectorStoreList) DeepCopy() *FoundryVectorStoreList {
	if in == nil {
		return nil
	}
	out := new(FoundryVectorStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FoundryVectorStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryVectorStoreObservation) DeepCopyInto(out *FoundryVectorStoreObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryVectorStoreObservation.
func (in *FoundryVectorStoreObservation) DeepCopy() *FoundryVectorStoreObservation {
	if in == nil {
		return nil
	}
	out := new(FoundryVectorStoreObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryVectorStoreParameters) DeepCopyInto(out *FoundryVectorStoreParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryVectorStoreParameters.
func (in *FoundryVectorStoreParameters) DeepCopy() *FoundryVectorStoreParameters {
	if in == nil {
		return nil
	}
	out := new(FoundryVectorStoreParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryVectorStoreSpec) DeepCopyInto(out *FoundryVectorStoreSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryVectorStoreSpec.
func (in *FoundryVectorStoreSpec) DeepCopy() *FoundryVectorStoreSpec {
	if in == nil {
		return nil
	}
	out := new(FoundryVectorStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FoundryVectorStoreStatus) DeepCopyInto(out *FoundryVectorStoreStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FoundryVectorStoreStatus.
func (in *FoundryVectorStoreStatus) DeepCopy() *FoundryVectorStoreStatus {
	if in == nil {
		return nil
	}
	out := new(FoundryVectorStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPTool) DeepCopyInto(out *MCPTool) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPTool.
func (in *MCPTool) DeepCopy() *MCPTool {
	if in == nil {
		return nil
	}
	out := new(MCPTool)
	in.DeepCopyInto(out)
	return out
}
